- name: Add homebrew tap repository
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - "{{ homebrew_taps }}"
  ignore_errors: yes
- name: Update homebrew
  homebrew: update_homebrew=yes
  ignore_errors: yes
- name: Install brew packages
  homebrew:
    name={{ item.name }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default('latest') | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items:
    "{{ homebrew_packages }}"
  ignore_errors: yes
- name: Install cask packages
  homebrew_cask:
    name={{ item.name }}
    state={{ item.state|default('installed') }}
  with_items:
    - "{{ homebrew_cask_packages }}"
  ignore_errors: yes