- name: Update homebrew
  homebrew: update_homebrew=yes
  ignore_errors: yes
- name: add Brewfile
  template:
    src: Brewfile
    dest:  ~/Brewfile
    owner: root
    group: root
    mode:  0755
- name: Install brew packages
  shell: "brew bundle --global"